'use strict';

const RoundConfig = require('../models/RoundConfig');

// Default initial competition rounds for auto-seeding
const DEFAULT_ROUNDS = [
  {
    roundNumber: 1,
    roundName: 'Round 1 - The First Crossing',
    budget: 5000000,
    buildTimeSeconds: 300,
    description: 'Construct a foundational bridge structure across the initial ravine.',
    isUnlockedByDefault: true
  },
  {
    roundNumber: 2,
    roundName: 'Round 2 - Heavy Logistics',
    budget: 3500000,
    buildTimeSeconds: 240,
    description: 'Sustain heavy vehicular transport with strict budget constraints.',
    isUnlockedByDefault: false
  },
  {
    roundNumber: 3,
    roundName: 'Round 3 - Elevation Asymmetry',
    budget: 4000000,
    buildTimeSeconds: 300,
    description: 'Engineer asymmetrical support structures across steep cliff heights.',
    isUnlockedByDefault: false
  }
];

/**
 * GET /api/admin/rounds
 * Returns all configured competition rounds. Auto-seeds defaults if empty.
 */
async function getRoundConfigsAdmin(req, res) {
  try {
    let rounds = await RoundConfig.find().sort({ roundNumber: 1 });

    if (!rounds || rounds.length === 0) {
      rounds = await RoundConfig.insertMany(DEFAULT_ROUNDS);
    }

    const nextRoundNumber = rounds.length > 0 ? Math.max(...rounds.map(r => r.roundNumber)) + 1 : 1;
    const autoGeneratedName = `Round ${nextRoundNumber} - Competition Phase ${nextRoundNumber}`;

    return res.status(200).json({
      success: true,
      data: rounds,
      nextRoundNumber,
      autoGeneratedName
    });
  } catch (err) {
    console.error('[adminRoundController] getRoundConfigsAdmin error:', err);
    return res.status(500).json({ success: false, message: 'Failed to fetch round configurations' });
  }
}

/**
 * POST /api/admin/rounds
 * Creates a new round. Auto-generates roundNumber and roundName if omitted.
 */
async function createRoundConfig(req, res) {
  try {
    let {
      roundNumber,
      roundName,
      budget,
      buildTimeSeconds,
      description
    } = req.body;

    const existingRounds = await RoundConfig.find().sort({ roundNumber: 1 });

    if (!roundNumber) {
      roundNumber = existingRounds.length > 0 ? Math.max(...existingRounds.map(r => r.roundNumber)) + 1 : 1;
    } else {
      roundNumber = Number(roundNumber);
    }

    const duplicate = await RoundConfig.findOne({ roundNumber });
    if (duplicate) {
      return res.status(400).json({ success: false, message: `Round number ${roundNumber} already exists` });
    }

    if (!roundName || !roundName.trim()) {
      roundName = `Round ${roundNumber} - Competition Phase ${roundNumber}`;
    } else {
      roundName = roundName.trim();
    }

    const round = await RoundConfig.create({
      roundNumber,
      roundName,
      budget: budget !== undefined ? Number(budget) : 4000000,
      buildTimeSeconds: buildTimeSeconds !== undefined ? Number(buildTimeSeconds) : 300,
      description: description ? description.trim() : 'Construct a structural bridge to sustain vehicular loads.',
      isUnlockedByDefault: roundNumber === 1
    });

    return res.status(201).json({
      success: true,
      message: `Round ${round.roundNumber} created successfully!`,
      data: round
    });
  } catch (err) {
    console.error('[adminRoundController] createRoundConfig error:', err);
    return res.status(500).json({ success: false, message: err.message || 'Server error creating round' });
  }
}

/**
 * PUT /api/admin/rounds/:id
 * Updates an existing round by ID
 */
async function updateRoundConfig(req, res) {
  try {
    const { id } = req.params;
    const updates = req.body;

    const round = await RoundConfig.findById(id);
    if (!round) {
      return res.status(404).json({ success: false, message: 'Round configuration not found' });
    }

    if (updates.roundName !== undefined) round.roundName = updates.roundName.trim();
    if (updates.budget !== undefined) round.budget = Number(updates.budget);
    if (updates.buildTimeSeconds !== undefined) round.buildTimeSeconds = Number(updates.buildTimeSeconds);
    if (updates.description !== undefined) round.description = updates.description.trim();

    await round.save();

    return res.status(200).json({
      success: true,
      message: `Round ${round.roundNumber} updated successfully`,
      data: round
    });
  } catch (err) {
    console.error('[adminRoundController] updateRoundConfig error:', err);
    return res.status(500).json({ success: false, message: 'Server error updating round' });
  }
}

/**
 * DELETE /api/admin/rounds/:id
 * Deletes a round configuration
 */
async function deleteRoundConfig(req, res) {
  try {
    const { id } = req.params;

    const round = await RoundConfig.findByIdAndDelete(id);
    if (!round) {
      return res.status(404).json({ success: false, message: 'Round configuration not found' });
    }

    return res.status(200).json({
      success: true,
      message: `Round ${round.roundNumber} deleted successfully`
    });
  } catch (err) {
    console.error('[adminRoundController] deleteRoundConfig error:', err);
    return res.status(500).json({ success: false, message: 'Server error deleting round' });
  }
}

module.exports = {
  getRoundConfigsAdmin,
  createRoundConfig,
  updateRoundConfig,
  deleteRoundConfig
};
